apiVersion: helm.hops.ops.com.ai/v1alpha1
kind: OpenSearch
metadata:
  name: opensearch
  namespace: example-env
spec:
  clusterName: example-cluster
  namespace: opensearch
  labels:
    team: platform
    environment: staging
  values:
    replicas: 3
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
